name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NVCC_FLAGS: "-allow-unsupported-compiler"
  TORCH_CUDA_ARCH_LIST: "8.6+PTX"
  DISTUTILS_USE_SDK: 1
  FORCE_CUDA: 1

jobs:
  build:
    runs-on: ${{ matrix.os-version }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os-version: windows-latest
            python-version: '3.10.9'
            cuda-version: '11.8.0'
            torch-install-command: 'torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118'

    steps:
      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ilammy/msvc-dev-cmd@v1
        id: msvc
        with:
          vsversion: 2022
      - id: prepare-build
        run: |
          git clone -b cmake_windows https://github.com/acpopescu/bitsandbytes
          cd bitsandbytes
          pip install ${{ matrix.torch-install-command }}
          pip install -r requirements.txt
          pip install wheel
      - uses: Jimver/cuda-toolkit@v0.2.10
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda-version }}
      - id: build
        env:
          CUDA_HOME: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}
        run: |
          cd bitsandbytes
          cmake -B win64
          cd win64
          msbuild libbitsandbytes_cuda.vcxproj /property:Configuration=Release
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*/*/*.dll"
          tag: ${{ github.run_id }}
          commit: ${{ github.sha }}
